### ISSUE TITLE
DFAST-core get a KeyError: 'WP_010895684'

### ISSUE THREAD

**Issue by ywangbio** [nigyta/dfast_core#24]
Now, I am comparing several genomes using their GFF3 files. To generate a GFF3 file, I ran DFAST-core with the genome sequence of CP003989.2 (Thioalkalivibrio nitratireducens DSM 14787) as an input file. However, DFAST-core did not finish its pipeline by giving a message 「KeyError: 'WP_010895684'」. However, on the DFAST server, I finished analysis and got a GFF3 file without any problem.

Could you help me to address this issue? Also, I would like to know what is the difference between the DFAST server and DFAST-core?

Here is the information for the analysis on the server:

JobID :  95c43c1e-e43d-4078-af23-2d1a6fa12dd9

Here is the DFAST-core pipeline information:

(base) conda3@conda3:~/Genome_seqs_for_tree$ dfast -g T_nitratireducens.fasta -o T_nitra_dFast --fix_origin --offset 100 --locus_tag_prefix T_nitra --step 1 --use_prodigal
2019/12/06 13:01:37 Running on Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0].
2019/12/06 13:01:37 Loading a config file from /home/conda3/miniconda3/opt/dfast-1.2.3/dfc/default_config.py
2019/12/06 13:01:37 OS type is Linux.
2019/12/06 13:01:37 Adding /home/conda3/miniconda3/opt/dfast-1.2.3/bin/Linux to PATH.
2019/12/06 13:01:37 [WARNING] Trying to locate a dnaA gene to fix the sequence origin of the chromosome. DO NOT APPLY THIS TO A DRAFT GENOME.
2019/12/06 13:01:42 DnaA gene was found at CP003989.2:3949099[+]. (E-val: 1.9e-179, score: 595.0)
2019/12/06 13:01:42 'CP003989.2' will be flipped/rotated so that the base position 3948999 comes first.
2019/12/06 13:01:42 Created a temporary file for the origin-fixed genome. (/tmp/tmpnogk25nd)
2019/12/06 13:01:42 DFAST pipeline started. (version 1.2.3)
2019/12/06 13:01:42 Results will be generated into 'T_nitra_dFast'.
2019/12/06 13:01:42 Loading a genomic fasta file from /tmp/tmpnogk25nd
2019/12/06 13:01:42 Genome source information: organism=, strain=
2019/12/06 13:01:42 The query genome is treated as a draft genome with 1 sequences.
2019/12/06 13:01:42 Sequences are sorted by length (from longer to shorter).
2019/12/06 13:01:42 Sequences shorter than 200 will be eliminated.
2019/12/06 13:01:42 Sequences will be renamed as sequence1, sequence2...
2019/12/06 13:01:42 Locus_tag settings: locus_tag_prefix=T_nitra and step=1.
2019/12/06 13:01:42 Locus_tags are assigned separately to each feature type. e.g. CDS: T_nitra_000xx, rRNA: T_nitra_r000xx, tRNA: T_nitra_t000xx, tmRNA: T_nitra_tm000xx.
2019/12/06 13:01:42 Remove_Partial_Feature is enabled.
2019/12/06 13:01:42 Remove_Overlapping_Feature is enabled. Priority: ['assembly_gap', 'CRISPR', ('tmRNA', 'tRNA', 'rRNA'), 'CDS']
2019/12/06 13:01:42 Initializing structural annotation tools... 
2019/12/06 13:01:42 GAPannotator initialized. (Version 1.0)
2019/12/06 13:01:42 Setting GAPannotator options. {'len_cutoff': 5, 'linkage_evidence': 'paired-ends', 'gap_type': 'within scaffold'}
2019/12/06 13:01:42 Checking Aragorn version... 
2019/12/06 13:01:42 Aragorn initialized. (Version 1.2.38)
2019/12/06 13:01:42 Setting Aragorn options. {'gcode': '-gcbact', 'cmd_options': '-l', 'transl_table': 11}
2019/12/06 13:01:42 Checking Barrnap version... 
2019/12/06 13:01:42 Barrnap initialized. (Version 0.8)
2019/12/06 13:01:42 Checking CRT version... 
2019/12/06 13:01:42 CRT initialized. (Version 1.2)
2019/12/06 13:01:42 Setting CRT options. {'jar_file': '/home/conda3/miniconda3/opt/dfast-1.2.3/bin/common/CRT1.2-CLI.jar', 'java_options': '', 'cmd_options': ''}
2019/12/06 13:01:42 Checking Java version... 
2019/12/06 13:01:42 Java initialized. (Version 11.0.1)
2019/12/06 13:01:43 Checking Prodigal version... 
2019/12/06 13:01:43 Prodigal initialized. (Version 2.6.3)
2019/12/06 13:01:43 Setting Prodigal options. {'transl_table': 11, 'cmd_options': ''}
2019/12/06 13:01:43 Initializing annotation components... 
2019/12/06 13:01:43 DBsearch initialized.
2019/12/06 13:01:43 Setting DBsearch options. {'skipAnnotatedFeatures': True, 'evalue_cutoff': 1e-06, 'qcov_cutoff': 75, 'scov_cutoff': 75, 'pident_cutoff': 0, 'aligner': 'ghostx', 'aligner_options': {}, 'database': '/home/conda3/miniconda3/opt/dfast-1.2.3/db/protein/DFAST-default.ref', 'db_name': ''}
2019/12/06 13:01:43 Checking GHOSTX version... 
2019/12/06 13:01:43 GHOSTX initialized. (Version 1.3.6)
2019/12/06 13:01:44 Reference DB loaded. 404961 sequences. [dbname=DFAST-default, version=1.1.5, contributor=yt, modified=20191106]
2019/12/06 13:01:44 PseudoGeneDetection initialized.
2019/12/06 13:01:44 Setting PseudoGeneDetection options. {'cpu': 1, 'skipAnnotatedFeatures': False, 'extension': 300, 'scov_cutoff': 85, 'transl_table': 11}
2019/12/06 13:01:44 Checking lastdb version... 
2019/12/06 13:01:44 lastdb initialized. (Version 959)
2019/12/06 13:01:44 Setting lastdb options. {'cpu': 1, 'skipAnnotatedFeatures': False, 'extension': 300, 'scov_cutoff': 85, 'transl_table': 11}
2019/12/06 13:01:44 Checking lastal version... 
2019/12/06 13:01:44 lastal initialized. (Version 959)
2019/12/06 13:01:44 Setting lastal options. {'cpu': 1, 'skipAnnotatedFeatures': False, 'extension': 300, 'scov_cutoff': 85, 'transl_table': 11}
2019/12/06 13:01:44 Checking Blastp version... 
2019/12/06 13:01:44 Blastp initialized. (Version 2.5.0)
2019/12/06 13:01:44 HMMscan initialized.
2019/12/06 13:01:44 Setting HMMscan options. {'skipAnnotatedFeatures': True, 'evalue_cutoff': 1e-06, 'database': '/home/conda3/miniconda3/opt/dfast-1.2.3/db/hmm/TIGRFAMs_15.0_HMM.LIB', 'db_name': 'TIGR'}
2019/12/06 13:01:44 Checking hmmscan version... 
2019/12/06 13:01:44 hmmscan initialized. (Version 3.2.1)
2019/12/06 13:01:44 Setting hmmscan options. {'skipAnnotatedFeatures': True, 'evalue_cutoff': 1e-06, 'database': '/home/conda3/miniconda3/opt/dfast-1.2.3/db/hmm/TIGRFAMs_15.0_HMM.LIB', 'db_name': 'TIGR'}
2019/12/06 13:01:44 CDDsearch initialized.
2019/12/06 13:01:44 Setting CDDsearch options. {'skipAnnotatedFeatures': False, 'evalue_cutoff': 1e-06, 'database': '/home/conda3/miniconda3/opt/dfast-1.2.3/db/cdd/Cog', 'rpsbproc_data': '/home/conda3/miniconda3/opt/dfast-1.2.3/bin/common/rpsbproc_data'}
2019/12/06 13:01:44 Checking RPSblast version... 
2019/12/06 13:01:44 RPSblast initialized. (Version 2.5.0)
2019/12/06 13:01:44 Setting RPSblast options. {'skipAnnotatedFeatures': False, 'evalue_cutoff': 1e-06, 'database': '/home/conda3/miniconda3/opt/dfast-1.2.3/db/cdd/Cog', 'rpsbproc_data': '/home/conda3/miniconda3/opt/dfast-1.2.3/bin/common/rpsbproc_data'}
2019/12/06 13:01:44 Checking rpsbproc version... 
2019/12/06 13:01:44 rpsbproc initialized. (Version 0.11)
2019/12/06 13:01:44 Setting rpsbproc options. {'skipAnnotatedFeatures': False, 'evalue_cutoff': 1e-06, 'database': '/home/conda3/miniconda3/opt/dfast-1.2.3/db/cdd/Cog', 'rpsbproc_data': '/home/conda3/miniconda3/opt/dfast-1.2.3/bin/common/rpsbproc_data'}
2019/12/06 13:01:44 Start structural annotation process using 1 CPUs
2019/12/06 13:01:57 0 assembly_gap features were detected by GAPannotator.
2019/12/06 13:01:57 50 tRNA features were detected by Aragorn.
2019/12/06 13:01:57 3 rRNA features were detected by Barrnap.
2019/12/06 13:01:57 8 CRISPR (later will be replaced by repeat_region) features were detected by CRT.
2019/12/06 13:01:58 3782 CDS features were detected by Prodigal.
2019/12/06 13:01:58 Removed 1 partial features.
2019/12/06 13:02:01 Removed 7 overlapping features.
2019/12/06 13:02:01 Start executing functional annotation components.
2019/12/06 13:02:01 DBsearch will be performed using 1 CPUs.
2019/12/06 13:03:22 DBsearch done 1/1.
2019/12/06 13:03:30 Last format DB will be performed using 1 CPUs.
2019/12/06 13:03:30 Last format DB done 1/1.
2019/12/06 13:03:30 Last alignment will be performed using 1 CPUs.
2019/12/06 13:03:32 Last alignment done 1/1.
2019/12/06 13:03:32 18 CDS features were marked as possible pseudo due to internal stop codons.
2019/12/06 13:03:32 85 CDS features were marked as possible pseudo due to frameshift.
2019/12/06 13:03:32 Internal stop codons in the following 2 CDSs are translated to selenosysteine/pyrrolysine, which will be annotated with 'transl_except'. ['Prodigal_1237', 'Prodigal_1016']
2019/12/06 13:03:32 Removed 2 CDSs. ['Prodigal_1238', 'Prodigal_1015']
Traceback (most recent call last):
  File "/home/conda3/miniconda3/bin/dfast", line 272, in <module>
    pipeline.execute()
  File "/home/conda3/miniconda3/opt/dfast-1.2.3/dfc/pipeline.py", line 54, in execute
    self.fa.execute()  # functional annotation
  File "/home/conda3/miniconda3/opt/dfast-1.2.3/dfc/functionalAnnotation.py", line 72, in execute
    component.run()
  File "/home/conda3/miniconda3/opt/dfast-1.2.3/dfc/components/PseudoGeneDetection.py", line 472, in run
    self.execute_blast(targets=proteins_with_transl_except)
  File "/home/conda3/miniconda3/opt/dfast-1.2.3/dfc/components/PseudoGeneDetection.py", line 462, in execute_blast
    _parse_result(blast_result_file)
  File "/home/conda3/miniconda3/opt/dfast-1.2.3/dfc/components/PseudoGeneDetection.py", line 432, in _parse_result
    protein = self.references[s_id]
KeyError: 'WP_010895684'

**Comment by nigyta** [comment]
Probably, this is due to the older version of Blast binaries (v.2.5.0). DFAST requires BLAST later than 2.6.0.
Please update BLAST by `conda update -c bioconda blast`

As for the difference between DFAST-core ad the web version, they are basically the same. The web version is just a web user-interface for DFAST-core. There might be small difference in terms of the versions of internally-used binaries (like BLAST).

**Comment by ywangbio** [comment]
I tried again after updating blast. However, I got the same result.

**Comment by nigyta** [comment]
Could you send the log file again?

Updating DFAST to ver1.2.4 or later may fix this. 
`conda update -c bioconda dfast`

**Comment by nigyta** [comment]
This may related to the issue reported here #17

**Comment by ywangbio** [comment]
By refering 「missing reference in pseudogene detection #17」, I did as followed:

First, download BLAST executables (ver2.6) from the DFAST repository.
$ wget https://github.com/nigyta/dfast_core/raw/master/bin/Linux/blastdbcmd
$ wget https://github.com/nigyta/dfast_core/raw/master/bin/Linux/blastp
$ wget https://github.com/nigyta/dfast_core/raw/master/bin/Linux/makeblastdb

Then, after adding execute permission as following
$ chmod a+x blastdbcmd blastp makeblastdb

move them to /home/USER/miniconda3/opt/dfast-X.X.X/bin/Linux/

After that, I ran DFAST-core. Perfectly, it works well.

The problem is that although I updated Blast, when I type 「blastp -version」, then I got 
「blastp: 2.5.0+
Package: blast 2.5.0, build Sep 20 2018 01:34:18」
It seems that the blast package did not updated. So directly download a new version from DFAST website is necessary to address this issue.

Thank you for your quick response.
