### ISSUE TITLE
HTTP Error 308: Permanent Redirect

### ISSUE THREAD

**Issue by Rui-Zzhang** [nigyta/dfast_core#35]
Hello DFAST developers, 

I received an HTTP error while running the database building step

dfast_file_downloader.py --protein dfast

#error messages: 
Traceback (most recent call last):
  File "/scratch/dfast_core-1.2.12/scripts/dfast_file_downloader.py", line 222, in <module>
    retrieved_file = retrieve_dfast_reference(db_name, out_dir)
  File "/scratch/ruizhang/dfast_core-1.2.12/scripts/dfast_file_downloader.py", line 106, in retrieve_dfast_reference
    request.urlretrieve(target_url, output_file)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.10/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.10/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.10/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.10/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.10/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.10/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.10/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 308: Permanent Redirect

Any insight to fix the issue? Thank you!

Rui

**Comment by nigyta** [comment]
Thank you for trying DFAST, @Rui-Zzhang 

Since DFAST web service moved to a new server in February 2021, the URL in the v1.2.12 is no longer accessible.

To avoid the HTTP error, please update the dfast_file_downloader.py script to the latest version (1.2.14), or
modify [Line-40 of the script]( https://github.com/nigyta/dfast_core/blob/be7eabb8beed0a5d5c1e7ea2b7e59463a579e111/scripts/dfast_file_downloader.py#L40) as following:

```
host_dfast = "https://dfast.nig.ac.jp"
```
to
```
host_dfast = "https://dfast.ddbj.nig.ac.jp"
```

Yasuhiro

**Comment by Rui-Zzhang** [comment]
Hi Yasuhiro, 

Thank you for your prompt reply, the issue has now been resolved!

Rui

**Comment by schraderL** [comment]
Hi, 
I get the same error when trying to install via conda. Could you update the conda package, so it works with the new server address?

Best
lukas
